allvars2018 = ['runId',
               'lumiSection',
               'eventId',
               'isData',
               'mcWeight',

               'pu_nTrueInt',
               'pu_nPUVert',
	       'nVtx',
               'hlt_trigName',
               'hlt_trigResult',
               'hlt_filterName',
               'hlt_filterResult',
               'pdfscaleSysWeights',

               'pfpatMet_smear',
               'pfMetCorrPt',
               'pfMetCorrPhi',
               'pfMetCorrUnc',
               'pfMetCorrSig',
               'pfpatCaloMETPt',
               'pfpatCaloMETPhi',
               'pfTRKMETPt_',
               'pfTRKMETPhi_',
	       'pfMetRawPt',
	       'pfMetRawPhi',

               'nEle',
               'elePx',
               'elePy',
               'elePz',
               'eleEnergy',
               'eleIsPassVeto',
               'eleIsPassLoose',
               'eleIsPassTight',
               'eleD0',
               'eleDz',
               'eleCharge',

               'nPho',
               'phoPx',
               'phoPy',
               'phoPz',
               'phoEnergy',
               'phoIsPassLoose',
               'phoIsPassTight',

               'nMu',
               'muPx',
               'muPy',
               'muPz',
               'muEnergy',
               'isLooseMuon',
               'isTightMuon',
               #'muChHadIso',
               #'muNeHadIso',
               #'muGamIso',
               #'muPUPt',
               'PFIsoLoose',  # -- < 0.25
               'PFIsoMedium',  # -- < 0.20
               'PFIsoTight',  # -- < 0.15
               'PFIsoVeryTight',  # -- < 0.10
               'muCharge',

               'HPSTau_n',
               'HPSTau_Px',
               'HPSTau_Py',
               'HPSTau_Pz',
               'HPSTau_Energy',
               'disc_decayModeFinding',
               'disc_againstElectronLooseMVA6',
               'disc_againstElectronMediumMVA6',
               'disc_againstElectronTightMVA6',
               'disc_againstMuonLoose3',
               'disc_againstMuonTight3',
               'disc_byVLooseIsolationMVArun2017v2DBoldDMwLT2017',
               'disc_byLooseIsolationMVArun2017v2DBoldDMwLT2017',
               'disc_byMediumIsolationMVArun2017v2DBoldDMwLT2017',
               'disc_byTightIsolationMVArun2017v2DBoldDMwLT2017',

               'nGenPar',
               'genParId',
               'genMomParId',
               'genParSt',
               'genParPx',
               'genParPy',
               'genParPz',
               'genParE',

               'THINnJet',
               'THINjetPx',
               'THINjetPy',
               'THINjetPz',
               'THINjetEnergy',
               'THINbRegNNResolution',
               'THINbRegNNCorr',
               'THINisPUJetIDLoose',
               'THINisPUJetIDMedium',
               'THINisPUJetIDTight',
               'THINjetPassIDTight',
               'THINjetDeepCSV_b',
               'THINjetHadronFlavor',
               'THINjetCEmEF',
               'THINjetCHadEF',
               'THINjetNEmEF',
               'THINjetNHadEF',
               'THINjetCMulti',
               'THINjetNMultiplicity',
               'THINjetCorrUncUp',
               'THINjetNPV',
	       'THINjetUncSources',
	       'THINjetUncTotal',

               'FATnJet',
               'FATjetPx',
               'FATjetPy',
               'FATjetPz',
               'FATjetEnergy',
               'FATgenjetpx',
               'FATgenjetpy',
               'FATgenjetpz',
               'FATgenjetE',
               'FATjetPassIDTight',
               'FATjetCEmEF',
               'FATjetCHadEF',
               'FATjetNEmEF',
               'FATjetNHadEF',
               'FATjetCMulti',
               'FATjetNMultiplicity',
               'FATjet_DoubleSV',
               'FATjet_probQCDb',
               'FATjet_probHbb',
               'FATjet_probQCDc',
               'FATjet_probHcc',
               'FATjet_probHbbc',
               'FATjet_prob_bbvsLight',
               'FATjet_prob_ccvsLight',
               'FATjet_prob_TvsQCD',
               'FATjet_prob_WvsQCD',
               'FATjet_prob_ZHbbvsQCD',
               'FATjetSDmass',
               'FATN2_Beta1_',
               'FATN2_Beta2_',
               'FATjetCHSPRmassL2L3Corr',
               'FATjetCHSSDmassL2L3Corr',
               'FATjetTau1',
               'FATjetTau2',
               'FATjetUncSources',
               'FATjetUncTotal',
               ]
allvars2017 = ['runId',
               'lumiSection',
               'eventId',
               'isData',
               'mcWeight',
               #'prefiringweight',
               #'prefiringweightup',
               #'prefiringweightdown',

               'pu_nTrueInt',
               'pu_nPUVert',
	       'nVtx',

               'hlt_trigName',
               'hlt_trigResult',
               'hlt_filterName',
               'hlt_filterResult',
               'pdfscaleSysWgtID_',
               'pdfscaleSysWeights',

               #'pfpatmodifiedMet_smear',
               'pfmodifiedMetCorrPt',
               'pfmodifiedMetCorrPhi',
               'pfmodifiedMetCorrUnc',
               'pfmodifiedMetCorrSig',
               'pfpatCaloMETPt',
               'pfpatCaloMETPhi',
               'pfTRKMETPt_',
               'pfTRKMETPhi_',

               'pfMetRawPt',
               'pfMetRawPhi',

               'nEle',
               'elePx',
               'elePy',
               'elePz',
               'eleEnergy',
               'eleIsPassVeto',
               'eleIsPassLoose',
               'eleIsPassTight',
               'eleD0',
               'eleDz',
               'eleCharge',
               'eleIsPassMedium',

               'nPho',
               'phoPx',
               'phoPy',
               'phoPz',
               'phoEnergy',
               'phoIsPassLoose',
               'phoIsPassTight',

               'nMu',
               'muPx',
               'muPy',
               'muPz',
               'muEnergy',
               'isLooseMuon',
               'isTightMuon',
               #'muChHadIso',
               #'muNeHadIso',
               #'muGamIso',
               #'muPUPt',
               'PFIsoLoose',  # -- < 0.25
               'PFIsoMedium',  # -- < 0.20
               'PFIsoTight',  # -- < 0.15
               'PFIsoVeryTight',  # -- < 0.10
               'muCharge',
               'isSoftMuon',

               'HPSTau_n',
               'HPSTau_Px',
               'HPSTau_Py',
               'HPSTau_Pz',
               'HPSTau_Energy',
               'disc_decayModeFinding',
               'disc_againstElectronLooseMVA6',
               'disc_againstElectronMediumMVA6',
               'disc_againstElectronTightMVA6',
               'disc_againstMuonLoose3',
               'disc_againstMuonTight3',
               #'disc_byVLooseIsolationMVArun2017v2DBoldDMwLT2017',
               #'disc_byLooseIsolationMVArun2017v2DBoldDMwLT2017',
               #'disc_byMediumIsolationMVArun2017v2DBoldDMwLT2017',
               #'disc_byTightIsolationMVArun2017v2DBoldDMwLT2017',
               'disc_decayModeFindingNewDMs',
               'disc_byVTightDeepTau2017v2p1VSjet',

               'nGenPar',
               'genParId',
               'genMomParId',
               'genParSt',
               'genParPx',
               'genParPy',
               'genParPz',
               'genParE',

               'THINnJet',
               'THINjetPx',
               'THINjetPy',
               'THINjetPz',
               'THINjetEnergy',
               'THINbRegNNResolution',
               'THINbRegNNCorr',
               'THINisPUJetIDLoose',
               'THINisPUJetIDMedium',
               'THINisPUJetIDTight',
               'THINjetPassIDTight',
               'THINjetDeepCSV_b',
               'THINjetHadronFlavor',
               'THINjetCEmEF',
               'THINjetCHadEF',
               'THINjetNEmEF',
               'THINjetNHadEF',
               'THINjetCMulti',
               'THINjetNMultiplicity',
               'THINjetCorrUncUp',
               'THINjetNPV',
               'THINjetUncSources',
               'THINjetUncTotal',
               'THINjetCISVV2',


               'FATnJet',
               'FATjetPx',
               'FATjetPy',
               'FATjetPz',
               'FATjetEnergy',
               'FATgenjetpx',
               'FATgenjetpy',
               'FATgenjetpz',
               'FATgenjetE',
               'FATjetPassIDTight',
               'FATjetCEmEF',
               'FATjetCHadEF',
               'FATjetNEmEF',
               'FATjetNHadEF',
               'FATjetCMulti',
               'FATjetNMultiplicity',
               'FATjet_DoubleSV',
               'FATjet_probQCDb',
               'FATjet_probHbb',
               'FATjet_probQCDc',
               'FATjet_probHcc',
               'FATjet_probHbbc',
               'FATjet_prob_bbvsLight',
               'FATjet_prob_ccvsLight',
               'FATjet_prob_TvsQCD',
               'FATjet_prob_WvsQCD',
               'FATjet_prob_ZHbbvsQCD',
               'FATjetSDmass',
               'FATN2_Beta1_',
               'FATN2_Beta2_',
               'FATjetCHSPRmassL2L3Corr',
               'FATjetCHSSDmassL2L3Corr',
               'FATjetTau1',
               'FATjetTau2',
               'FATjetUncSources',
               'FATjetUncTotal',

               'THINjetNTracks',
               'THINjetTrackImpdz',
               'THINjetTrackImpdzError',
               'THINjetTrackImpdxy',
               'THINjetTrackImpdxyError',
               'THINjetTrackPt',
               'THINjetTrackEta',
               'THINjetTrackPhi',
               'THINjetTrackStatus',
               'THINjetTrackHighPurity',
               ]

allvars2016 = ['runId',
               'lumiSection',
               'eventId',
               'isData',
               'mcWeight',
               'prefiringweight',
               'prefiringweightup',
               'prefiringweightdown',

               'pu_nTrueInt',
               'pu_nPUVert',
	       'nVtx',
               'hlt_trigName',
               'hlt_trigResult',
               'hlt_filterName',
               'hlt_filterResult',
               'pdfscaleSysWgtID_',
               'pdfscaleSysWeights',

               'pfpatMet_smear',
               'pfMetCorrPt',
               'pfMetCorrPhi',
               'pfMetCorrUnc',
               'pfMetCorrSig',
               'pfpatCaloMETPt',
               'pfpatCaloMETPhi',
               'pfTRKMETPt_',
               'pfTRKMETPhi_',
               'pfMetRawPt',
               'pfMetRawPhi',


               'nEle',
               'elePx',
               'elePy',
               'elePz',
               'eleEnergy',
               'eleIsPassVeto',
               'eleIsPassLoose',
               'eleIsPassTight',
               'eleD0',
               'eleDz',
               'eleCharge',

               'nPho',
               'phoPx',
               'phoPy',
               'phoPz',
               'phoEnergy',
               'phoIsPassLoose',
               'phoIsPassTight',

               'nMu',
               'muPx',
               'muPy',
               'muPz',
               'muEnergy',
               'isLooseMuon',
               'isTightMuon',
               #'muChHadIso',
               #'muNeHadIso',
               #'muGamIso',
               #'muPUPt',
               'PFIsoLoose',  # -- < 0.25
               'PFIsoMedium',  # -- < 0.20
               'PFIsoTight',  # -- < 0.15
               'PFIsoVeryTight',  # -- < 0.10
               'muCharge',

               'HPSTau_n',
               'HPSTau_Px',
               'HPSTau_Py',
               'HPSTau_Pz',
               'HPSTau_Energy',
               'disc_decayModeFinding',
               'disc_againstElectronLooseMVA6',
               'disc_againstElectronMediumMVA6',
               'disc_againstElectronTightMVA6',
               'disc_againstMuonLoose3',
               'disc_againstMuonTight3',
               'disc_byVLooseIsolationMVArun2017v2DBoldDMwLT2017',
               'disc_byLooseIsolationMVArun2017v2DBoldDMwLT2017',
               'disc_byMediumIsolationMVArun2017v2DBoldDMwLT2017',
               'disc_byTightIsolationMVArun2017v2DBoldDMwLT2017',

               'nGenPar',
               'genParId',
               'genMomParId',
               'genParSt',
               'genParPx',
               'genParPy',
               'genParPz',
               'genParE',

               'THINnJet',
               'THINjetPx',
               'THINjetPy',
               'THINjetPz',
               'THINjetEnergy',
               'THINbRegNNResolution',
               'THINbRegNNCorr',
               'THINisPUJetIDLoose',
               'THINisPUJetIDMedium',
               'THINisPUJetIDTight',
               'THINjetPassIDLoose',
               'THINjetDeepCSV_b',
               'THINjetHadronFlavor',
               'THINjetCEmEF',
               'THINjetCHadEF',
               'THINjetNEmEF',
               'THINjetNHadEF',
               'THINjetCMulti',
               'THINjetNMultiplicity',
               'THINjetCorrUncUp',
               'THINjetNPV',
               'THINjetUncSources',
               'THINjetUncTotal',


               'FATnJet',
               'FATjetPx',
               'FATjetPy',
               'FATjetPz',
               'FATjetEnergy',
               'FATgenjetpx',
               'FATgenjetpy',
               'FATgenjetpz',
               'FATgenjetE',
               'FATjetPassIDLoose',
               'FATjetCEmEF',
               'FATjetCHadEF',
               'FATjetNEmEF',
               'FATjetNHadEF',
               'FATjetCMulti',
               'FATjetNMultiplicity',
               'FATjet_DoubleSV',
               'FATjet_probQCDb',
               'FATjet_probHbb',
               'FATjet_probQCDc',
               'FATjet_probHcc',
               'FATjet_probHbbc',
               'FATjet_prob_bbvsLight',
               'FATjet_prob_ccvsLight',
               'FATjet_prob_TvsQCD',
               'FATjet_prob_WvsQCD',
               'FATjet_prob_ZHbbvsQCD',
               'FATjetSDmass',
               'FATN2_Beta1_',
               'FATN2_Beta2_',
               'FATjetCHSPRmassL2L3Corr',
               'FATjetCHSSDmassL2L3Corr',
               'FATjetTau1',
               'FATjetTau2',
               'FATjetUncSources',
               'FATjetUncTotal',

               ]
